version: '3'

services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: til-app
      POSTGRES_PASSWORD: til-app
      POSTGRES_DB: til-app
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
    volumes:
      - ./dist/data:/var/lib/til-app/data
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/usr/src
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - '3000:3000'
