version: '3'

services:
  postgres:
    container_name: 'til-db'
    image: postgres:14.0
    environment:
      POSTGRES_USER: til-app
      POSTGRES_PASSWORD: til-app
      POSTGRES_DB: til-app
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
    volumes:
      - ./dist/data:/var/lib/til-app/data

  til-app:
    container_name: 'til-app'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://til-app:til-app@postgres:5432/til-app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    tty: true
